### ISSUE TITLE
any benchmarks result on this dataset?

### ISSUE THREAD

**Issue by opconty** [HCIILAB/TKH_MTH2200_Datasets_Release#1]
Hi,
I am working on Chinese Text Detection and recognition,this dataset spurs me to take a further step to do more .
Are there any benchmarks result on this dataset?

Thanks.

**Comment by WeihongM** [comment]
More information can find from this paper. [Link](https://arxiv.org/abs/2007.06890)

**Comment by opconty** [comment]
ok, I'll check that, thanks
